### ISSUE TITLE
BDInfo: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by hummingbirdy2** [dotnetcorecorner/BDInfo#4]
**Describe the bug**
Every time I try to run BDInfo I have this error: `The value must be greater than or equal to zero and less than the console's buffer size in that dimension.` 

**To Reproduce**
1. Open PowerShell (same problem on cmd.exe)
2. `cd C:\Tools\BDInfo`
3. `.\BDInfo.exe -p "E:\Movie Name (XXXX)\My.Movie.Folder"`
4. The error happen just after

**Expected behavior**
This repository works with the BDInfo v0.7.5.8b

**Error log**
```log
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 30.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at BDInfo.Program.SetCursorPosition(Int32 left, Int32 top) in D:\a\BDInfo\BDInfo\BDInfo.Core\BDInfo\Program.cs:line 1631
   at BDInfo.Program.OnTextChanged(String obj, Int32 position) in D:\a\BDInfo\BDInfo\BDInfo.Core\BDInfo\Program.cs:line 170
   at BDCommon.ListElement.set_Text(String value) in D:\a\BDInfo\BDInfo\BDInfo.Core\BDCommon\ListElement.cs:line 18
   at BDInfo.Program.InitBDROMCompleted(Object result) in D:\a\BDInfo\BDInfo\BDInfo.Core\BDInfo\Program.cs:line 243
   at BDInfo.Program.InitBDROM(String path) in D:\a\BDInfo\BDInfo\BDInfo.Core\BDInfo\Program.cs:line 182
   at BDInfo.Program.Exec(CmdOptions opts) in D:\a\BDInfo\BDInfo\BDInfo.Core\BDInfo\Program.cs:line 83
```

**Version**
 - OS: Windows 10 64bit (19043.1526)
 - PowerShell Version: 7.2.1
 - BDInfo Version: 1.0.3

**Comment by Sonic3R** [comment]
Can test by adding -d in command ?

**Comment by Sonic3R** [comment]
I will fix the issue that happens without that -d argument

**Comment by Sonic3R** [comment]
@hummingbirdy2 

Well, I can't reproduce issue, can tell me the width and height of powershell window ? Or do you use ISE environment to edit powershell script ?
